paths:
  raw_dir: "./data/kb/raw"
  processed_dir: "./data/kb/processed"
  docstore_dir: "./data/kb/docstore"
  index_dir: "./data/kb/index"
  cache_dir: "./data/kb/cache"
  observability_dir: "./observability"
  eval_dir: "./eval"

embedding:
  model_name: "BAAI/bge-large-en-v1.5"
  batch_size: 16
  device: "cuda"

retrieval:
  top_k_retrieve: 30
  top_k_final: 8
  use_bm25: false
  min_rerank_score: 0.20 
reranker:
  model_name: "BAAI/bge-reranker-base"
  device: "cuda"

chunking:
  target_tokens: 1000
  overlap_tokens: 150
  min_chars_for_index: 1
llm:
  provider: "none"
  base_url: ""
  model: "Qwen-14B-Instruct"
